ALTER TABLE ADDRESSES ADD CONSTRAINT ADDRESSES_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE ADVERTISEMENTCONTACTS ADD CONSTRAINT CONTACTS_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE ADVERTISEMENTCONTACTS ADD CONSTRAINT CONTACTS_BRANCHID_FK FOREIGN KEY (BRANCH_ID)
	REFERENCES BRANCHES (ID);

ALTER TABLE ADVERTISEMENTS ADD CONSTRAINT REQUIREDSKILLS FOREIGN KEY (REQUIREDSKILLID)
	REFERENCES REQUIREDSKILLS (REQUIREDSKILLID);

ALTER TABLE ADVERTISEMENTS ADD CONSTRAINT ADVERTCONTACTS_FK FOREIGN KEY (ADVERTCONTACTID)
	REFERENCES ADVERTISEMENTCONTACTS (ADVERTCONTACTID);

ALTER TABLE ADVERTISEMENTS ADD CONSTRAINT SITES_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE ADVERTISEMENTS_EXT_SITES ADD CONSTRAINT ADVERTISEMENT_EXT_ADV_FK_1 FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE ADVERTISEMENT_LANGUAGES ADD CONSTRAINT ADVERTISEMENT_LANG_ADV_FK_1 FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE ADVERTISEMENT_LOCATIONS ADD CONSTRAINT ADVERTISEMENT_LOC_ADV_FK_1 FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE ADVERTISEMENT_SITES ADD CONSTRAINT ADVERTISEMENT_SITES_ADV_FK_1 FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE ADVERTISEMENT_SITES ADD CONSTRAINT ADVERTISEMENT_SITES_SITES_FK_2 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID)
	ON DELETE CASCADE;

ALTER TABLE BRANCHES ADD CONSTRAINT BRANCH_SITE_FK_PK_1_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATECOVERLETTERS ADD CONSTRAINT COVE_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATECOVERLETTERS ADD CONSTRAINT COVER_SITE_FK_ID FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEEDUCATIONS ADD CONSTRAINT EDU_CANDI-FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEEDUCATIONS ADD CONSTRAINT EDUCATION_SITESID_FK_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEJOBAGENTS ADD CONSTRAINT CANDIDATEJOBAGENTS_CANDID_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEJOBAGENTS ADD CONSTRAINT CANDIDATEJOBAGENTS_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEJOBAPPLICATIONS ADD CONSTRAINT JOBAPPLI_SITES_ID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEJOBAPPLICATIONS ADD CONSTRAINT JOBAPLI_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEJOBAPPLICATIONS ADD CONSTRAINT JOBAPPLI_ADVER_ID_FK FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEJOBHISTORIES ADD CONSTRAINT HISTO_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEJOBHISTORIES ADD CONSTRAINT JOBHIS_SITE_ID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEPREFERENCES ADD CONSTRAINT CANDIDATEPREFERENCES_CANDID_PK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEPREFERENCES ADD CONSTRAINT CANDIDATEPREFERENCES_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATEREFERENCES ADD CONSTRAINT CANDIDATEREFERENCES_CANDID_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATEREFERENCES ADD CONSTRAINT CANDIDATEREFERENCES_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATERESUMES ADD CONSTRAINT RESU_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATERESUMES ADD CONSTRAINT RESU_SITE_FK_ID FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATES ADD CONSTRAINT CANDIDATES_BRANCHID_FK FOREIGN KEY (BRANCH_ID)
	REFERENCES BRANCHES (ID)
	DISABLE;

ALTER TABLE CANDIDATES ADD CONSTRAINT CANDIDATES_SITE_ID_FK_1_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATESAVEJOBS ADD CONSTRAINT SAVEJOBS_ADVERT_FK FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATESAVEJOBS ADD CONSTRAINT SAVEJOBS_CANDID_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CANDIDATESAVEJOBS ADD CONSTRAINT SAVEJOBS_SITE_ID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATESKILLS ADD CONSTRAINT CANDIDATESKILLS_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CANDIDATESKILLS ADD CONSTRAINT CANDIDATESKILLS_SKILLID_FK FOREIGN KEY (SKILLS_ID)
	REFERENCES SKILLS (ID);

ALTER TABLE CANDIDATESKILLS ADD CONSTRAINT CANDIDATESKILLS_CANDID_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE CONFIGURATION ADD CONSTRAINT CONF_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CONSENT ADD CONSTRAINT CONSENT_SITESID_FK_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE CONSENT ADD CONSTRAINT CONSENT_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE EMAILS ADD CONSTRAINT SITES_FK_EMAILS FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE EMAILS ADD CONSTRAINT CANDIDATES_FK_EMAILS FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID);

ALTER TABLE EMAILS ADD CONSTRAINT CANDIDATEREFERENCES_FK_E FOREIGN KEY (CANDIDATEREFERENCE_ID)
	REFERENCES CANDIDATEREFERENCES (ID);

ALTER TABLE FLEX_FIELD ADD CONSTRAINT FLEX_FIELD_CANDI_FK_ID FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE FLEX_FIELD ADD CONSTRAINT FLEX_FIELD_SITESID_FK_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE HISTORYLOG ADD CONSTRAINT HISTORYLOG_CAND_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE HISTORYLOG ADD CONSTRAINT HISTORYLOG_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE LOOKUP_VALUES ADD CONSTRAINT FK_LOOKUP_VALUES_SITES_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE LOSTCANDIDATES ADD CONSTRAINT LOSTCANDIDATES_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE OTHER_CANDIDATE_DETAILS ADD CONSTRAINT FK_OCD_BY_CANDIDATE FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID);

ALTER TABLE OTHER_CANDIDATE_DETAILS ADD CONSTRAINT FK_OCD_BY_SITE FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE PERSONS ADD CONSTRAINT PERSON_SITE_ID_FK_1_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE PERSONS ADD CONSTRAINT PERSON_USER_ID_FK_1_1 FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	DISABLE;

ALTER TABLE PHONES ADD CONSTRAINT PHONES_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE PHONES ADD CONSTRAINT PHONES_CANDID_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE RECRUITERCOMMENTS ADD CONSTRAINT RECRUITERCOMMENTS_CAND_FK FOREIGN KEY (CANDIDATE_ID)
	REFERENCES CANDIDATES (ID)
	ON DELETE CASCADE;

ALTER TABLE RECRUITERCOMMENTS ADD CONSTRAINT RECRUITERCOMMENTS_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE RECRUITERCOMMENTS ADD CONSTRAINT RECRUITERCOMMENTS_RECID_FK FOREIGN KEY (RECRUITER_ID)
	REFERENCES ADVERTISEMENTCONTACTS (ADVERTCONTACTID);

ALTER TABLE REQUIREDSKILLS ADD CONSTRAINT REQUIREDSKILL_ADVER_FK_1_1 FOREIGN KEY (ADVERTISEMENT_ID)
	REFERENCES ADVERTISEMENTS (ADVERTISEMENTID)
	ON DELETE CASCADE;

ALTER TABLE REQUIREDSKILLS ADD CONSTRAINT REQUI_SITE_FK_ID_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID)
	ON DELETE CASCADE;

ALTER TABLE SKILLS ADD CONSTRAINT SKILL_SITE_ID_FK_1_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE STEERING_QUESTIONS ADD CONSTRAINT STEERING_QUESTIONS_SITEID_FK FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE USERLOGINHISTORIES ADD CONSTRAINT HISTORIES_SITE_ID_FK_1_1 FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE USERLOGINHISTORIES ADD CONSTRAINT HISTORIES_USER_ID_FK_1_1 FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID);

ALTER TABLE USERS ADD CONSTRAINT SITE_ID_FKSITES FOREIGN KEY (SITE_ID)
	REFERENCES SITES (ID);

ALTER TABLE USERS ADD CONSTRAINT USERROLE_ID_FKROLES FOREIGN KEY (USERROLE_ID)
	REFERENCES USERROLES (ID);

