ALTER TABLE ADDRESSES DROP CONSTRAINT ADDRESSES_SITEID_FK;

ALTER TABLE ADVERTISEMENTCONTACTS DROP CONSTRAINT CONTACTS_SITEID_FK;

ALTER TABLE ADVERTISEMENTCONTACTS DROP CONSTRAINT CONTACTS_BRANCHID_FK;

ALTER TABLE ADVERTISEMENTS DROP CONSTRAINT REQUIREDSKILLS;

ALTER TABLE ADVERTISEMENTS DROP CONSTRAINT ADVERTCONTACTS_FK;

ALTER TABLE ADVERTISEMENTS DROP CONSTRAINT SITES_FK;

ALTER TABLE ADVERTISEMENTS_EXT_SITES DROP CONSTRAINT ADVERTISEMENT_EXT_ADV_FK_1;

ALTER TABLE ADVERTISEMENT_LANGUAGES DROP CONSTRAINT ADVERTISEMENT_LANG_ADV_FK_1;

ALTER TABLE ADVERTISEMENT_LOCATIONS DROP CONSTRAINT ADVERTISEMENT_LOC_ADV_FK_1;

ALTER TABLE ADVERTISEMENT_LOCATIONS DROP CONSTRAINT ADVERTISEMENT_LOCATIONS_FK_2;

ALTER TABLE ADVERTISEMENT_SITES DROP CONSTRAINT ADVERTISEMENT_SITES_ADV_FK_1;

ALTER TABLE ADVERTISEMENT_SITES DROP CONSTRAINT ADVERTISEMENT_SITES_SITES_FK_2;

ALTER TABLE BRANCHES DROP CONSTRAINT BRANCH_SITE_FK_PK_1_1;

ALTER TABLE CANDIDATECOVERLETTERS DROP CONSTRAINT COVE_CANDI_FK_ID;

ALTER TABLE CANDIDATECOVERLETTERS DROP CONSTRAINT COVER_SITE_FK_ID;

ALTER TABLE CANDIDATEEDUCATIONS DROP CONSTRAINT EDU_CANDI-FK_ID;

ALTER TABLE CANDIDATEEDUCATIONS DROP CONSTRAINT EDUCATION_SITESID_FK_1;

ALTER TABLE CANDIDATEJOBAGENTS DROP CONSTRAINT CANDIDATEJOBAGENTS_CANDID_FK;

ALTER TABLE CANDIDATEJOBAGENTS DROP CONSTRAINT CANDIDATEJOBAGENTS_SITEID_FK;

ALTER TABLE CANDIDATEJOBAPPLICATIONS DROP CONSTRAINT JOBAPPLI_SITES_ID_FK;

ALTER TABLE CANDIDATEJOBAPPLICATIONS DROP CONSTRAINT JOBAPLI_CANDI_FK_ID;

ALTER TABLE CANDIDATEJOBAPPLICATIONS DROP CONSTRAINT JOBAPPLI_ADVER_ID_FK;

ALTER TABLE CANDIDATEJOBHISTORIES DROP CONSTRAINT HISTO_CANDI_FK_ID;

ALTER TABLE CANDIDATEJOBHISTORIES DROP CONSTRAINT JOBHIS_SITE_ID_FK;

ALTER TABLE CANDIDATEPREFERENCES DROP CONSTRAINT CANDIDATEPREFERENCES_CANDID_PK;

ALTER TABLE CANDIDATEPREFERENCES DROP CONSTRAINT CANDIDATEPREFERENCES_SITEID_FK;

ALTER TABLE CANDIDATEREFERENCES DROP CONSTRAINT CANDIDATEREFERENCES_CANDID_FK;

ALTER TABLE CANDIDATEREFERENCES DROP CONSTRAINT CANDIDATEREFERENCES_SITEID_FK;

ALTER TABLE CANDIDATERESUMES DROP CONSTRAINT RESU_CANDI_FK_ID;

ALTER TABLE CANDIDATERESUMES DROP CONSTRAINT RESU_SITE_FK_ID;

ALTER TABLE CANDIDATES DROP CONSTRAINT CANDIDATES_BRANCHID_FK;

ALTER TABLE CANDIDATES DROP CONSTRAINT CANDIDATES_SITE_ID_FK_1_1;

ALTER TABLE CANDIDATESAVEJOBS DROP CONSTRAINT SAVEJOBS_ADVERT_FK;

ALTER TABLE CANDIDATESAVEJOBS DROP CONSTRAINT SAVEJOBS_CANDID_FK;

ALTER TABLE CANDIDATESAVEJOBS DROP CONSTRAINT SAVEJOBS_SITE_ID_FK;

ALTER TABLE CANDIDATESKILLS DROP CONSTRAINT CANDIDATESKILLS_SITEID_FK;

ALTER TABLE CANDIDATESKILLS DROP CONSTRAINT CANDIDATESKILLS_SKILLID_FK;

ALTER TABLE CANDIDATESKILLS DROP CONSTRAINT CANDIDATESKILLS_CANDID_FK;

ALTER TABLE CONFIGURATION DROP CONSTRAINT CONF_SITEID_FK;

ALTER TABLE CONSENT DROP CONSTRAINT CONSENT_SITESID_FK_1;

ALTER TABLE CONSENT DROP CONSTRAINT CONSENT_CANDI_FK_ID;

ALTER TABLE EMAILS DROP CONSTRAINT SITES_FK_EMAILS;

ALTER TABLE EMAILS DROP CONSTRAINT CANDIDATES_FK_EMAILS;

ALTER TABLE EMAILS DROP CONSTRAINT CANDIDATEREFERENCES_FK_E;

ALTER TABLE FLEX_FIELD DROP CONSTRAINT FLEX_FIELD_CANDI_FK_ID;

ALTER TABLE FLEX_FIELD DROP CONSTRAINT FLEX_FIELD_SITESID_FK_1;

ALTER TABLE HISTORYLOG DROP CONSTRAINT HISTORYLOG_CAND_FK;

ALTER TABLE HISTORYLOG DROP CONSTRAINT HISTORYLOG_SITEID_FK;

ALTER TABLE LOOKUP_VALUES DROP CONSTRAINT FK_LOOKUP_VALUES_SITES_1;

ALTER TABLE LOSTCANDIDATES DROP CONSTRAINT LOSTCANDIDATES_SITEID_FK;

ALTER TABLE OTHER_CANDIDATE_DETAILS DROP CONSTRAINT FK_OCD_BY_CANDIDATE;

ALTER TABLE OTHER_CANDIDATE_DETAILS DROP CONSTRAINT FK_OCD_BY_SITE;

ALTER TABLE PERSONS DROP CONSTRAINT PERSON_SITE_ID_FK_1_1;

ALTER TABLE PERSONS DROP CONSTRAINT PERSON_USER_ID_FK_1_1;

ALTER TABLE PHONES DROP CONSTRAINT PHONES_SITEID_FK;

ALTER TABLE PHONES DROP CONSTRAINT PHONES_CANDID_FK;

ALTER TABLE RECRUITERCOMMENTS DROP CONSTRAINT RECRUITERCOMMENTS_CAND_FK;

ALTER TABLE RECRUITERCOMMENTS DROP CONSTRAINT RECRUITERCOMMENTS_SITEID_FK;

ALTER TABLE RECRUITERCOMMENTS DROP CONSTRAINT RECRUITERCOMMENTS_RECID_FK;

ALTER TABLE REQUIREDSKILLS DROP CONSTRAINT REQUIREDSKILL_ADVER_FK_1_1;

ALTER TABLE REQUIREDSKILLS DROP CONSTRAINT REQUI_SITE_FK_ID_1;

ALTER TABLE SKILLS DROP CONSTRAINT SKILL_SITE_ID_FK_1_1;

ALTER TABLE STEERING_QUESTIONS DROP CONSTRAINT STEERING_QUESTIONS_SITEID_FK;

ALTER TABLE USERLOGINHISTORIES DROP CONSTRAINT HISTORIES_SITE_ID_FK_1_1;

ALTER TABLE USERLOGINHISTORIES DROP CONSTRAINT HISTORIES_USER_ID_FK_1_1;

ALTER TABLE USERS DROP CONSTRAINT SITE_ID_FKSITES;

ALTER TABLE USERS DROP CONSTRAINT USERROLE_ID_FKROLES;