package com.asponte.portal.designer.wcm;


public interface Constants {
	/* Widget Types */
	String CONTENT_TYPE="content";
	String LIST_TYPE="list";
	String COMPOSITE_LIST_TYPE="composite";
	String NONE_TYPE="none";
	
	/* LRP Parameter Keys */
	String WCM_LISTENS_TO_PREF = "WCM_LISTENS_TO";
	String WCM_BROADCASTS_TO_PREF = "WCM_BROADCASTS_TO";
	String WCM_COMPONENT_IDR_PREF = "WCM_COMPONENT_IDR";
	String WCM_CONTENT_CONTEXT_IDR_PREF = "WCM_CONTENT_CONTEXT_IDR";
	String WCM_CONTENT_CONTEXT_TYPE_PREF = "WCM_CONTENT_CONTEXT_TYPE";
	String WCM_CONTENT_TYPE_PREF = "WCM_CONTENT_TYPE";
	String WCM_CATEGORY_OVERRIDE_PREF="CATEGORY_OVERRIDE";
	String WCM_SITEAREA_OVERRIDE_PREF="SITEAREA_OVERRIDE";
	String WCM_PORTLET_TITLE_PREF="WCM_PORTLET_TITLE";
	String WCM_PORTLET_TITLE_TYPE_PREF="WCM_PORTLET_TITLE_TYPE";
	
	/* LRP Parameter Values */
	String WCM_CONTENT_CONTEXT_TYPE="content";
	String WCM_SITEAREA_CONTEXT_TYPE="sitearea";
	String WCM_CONTENT_TYPE="CONTENT";
	String WCM_COMPONENT_TYPE="COMPONENT";
	String WCM_LINKING_SELF="WCM_LINKING_SELF";
	String WCM_LINKING_OTHER="WCM_LINKING_OTHER";
	String WCM_LINKING_NONE="WCM_LINKING_NONE";
	String WCM_LINKING_DYNAMIC="WCM_LINKING_DYNAMIC";
	String WCM_PORTLET_TITLE_TYPE_GENERAL="WCM_PORTLET_TITLE_TYPE_GENERAL";
	String WCM_PORTLET_TITLE_TYPE_DYN="WCM_PORTLET_TITLE_TYPE_DYN";
	String WCM_PORTLET_TITLE_TYPE_DEFAULT="WCM_PORTLET_TITLE_TYPE_DEFAULT";
	
	/* Reserved Content Component Names */
	String STYLE_CMPNT_NAME="aww_Style";
	String WRAPPER_CMPNT_NAME="aww_Component";
}
